# Generated by Django 4.2.3 on 2023-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('DOB', models.CharField(max_length=200)),
                ('AGE', models.CharField(max_length=200)),
                ('GENDER', models.CharField(max_length=10)),
                ('PHONE_NUMBER', models.CharField(max_length=15)),
                ('MAIL_ID', models.EmailField(max_length=254)),
                ('ADDRESS', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FormApp',
            },
        ),
    ]
