# Generated by Django 4.2.3 on 2023-10-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_store_app', '0002_school_store_app_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='school_store_app',
        ),
    ]
